version: '3'
services:
  nats-server:
    image: nats
    container_name: nats
    ports:
      - 4222:4222

  upload-service:
    build: 
      context: ./upload-service/
    image: upload-service:latest
    ports:
      - '8080:8080'
    links:
      - nats-server
    environment:
      - "NATS_URL=nats://nats:4222"
  
  alerting-service:
    build: 
      context: ./alerting-service/
    image: alerting-service:latest
    links:
      - nats-server
    environment:
      - "NATS_URL=nats://nats:4222"